# Generated by Django 5.2.5 on 2025-08-23 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estadocivil_genero_nacionalidade_profissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='compl_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='dataCad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='idUserQueCadJud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pj_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='num_end',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='tipoPessoa',
            field=models.CharField(default='J', max_length=2),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='todos',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=18, null=True),
        ),
    ]
