# Generated by Django 5.2.5 on 2025-08-23 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pessoajuridica_bairro_pessoajuridica_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeTituloProc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoTitulo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusProc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusProc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrevNomeForum', models.CharField(blank=True, max_length=50, null=True)),
                ('nomeForum', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=300, null=True)),
                ('num_end', models.CharField(blank=True, max_length=11, null=True)),
                ('compl_end', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('ultimaAlteracao', models.DateTimeField(auto_now=True)),
                ('idUserQueAlterou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='foruns_alterados', to=settings.AUTH_USER_MODEL)),
                ('idUserQueCadastrou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='foruns_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numProc', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('valorCausa', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('dataDistribuicao', models.DateField(blank=True, null=True)),
                ('dataCad', models.DateTimeField(auto_now_add=True)),
                ('dataAlteracao', models.DateField(blank=True, null=True)),
                ('InstanciaProc', models.CharField(blank=True, max_length=50, null=True)),
                ('idAlteradoPorUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='processos_alterados', to=settings.AUTH_USER_MODEL)),
                ('idTblForum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.forum')),
                ('idStatusProc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.statusproc')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPasta', models.IntegerField(blank=True, null=True)),
                ('idTblProc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.processo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoProc', models.CharField(blank=True, max_length=50, null=True)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('dataAlteracao', models.DateField(blank=True, null=True)),
                ('idAlteradoPorUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tipoproc_alterados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='idTblTipoProc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.tipoproc'),
        ),
        migrations.CreateModel(
            name='TituloProcAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeTituloProc', models.CharField(blank=True, max_length=200, null=True)),
                ('autor', models.CharField(blank=True, max_length=45, null=True)),
                ('dataAlteracao', models.DateField(blank=True, null=True)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('numPasta', models.IntegerField(blank=True, null=True)),
                ('idAlteradoPorUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='titulos_autor_alterados', to=settings.AUTH_USER_MODEL)),
                ('idTblProc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.processo')),
            ],
        ),
        migrations.CreateModel(
            name='TituloProcReu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeTituloProc', models.CharField(blank=True, max_length=200, null=True)),
                ('reu', models.CharField(blank=True, max_length=50, null=True)),
                ('dataAlteracao', models.DateField(blank=True, null=True)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('numPasta', models.CharField(blank=True, max_length=50, null=True)),
                ('idAlteradoPorUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='titulos_reu_alterados', to=settings.AUTH_USER_MODEL)),
                ('idTblProc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.processo')),
            ],
        ),
        migrations.CreateModel(
            name='Vara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrevNomeVara', models.CharField(blank=True, max_length=50, null=True)),
                ('numVara', models.CharField(blank=True, max_length=3, null=True)),
                ('nomeVara', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=300, null=True)),
                ('num_end', models.CharField(blank=True, max_length=11, null=True)),
                ('compl_end', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('ultimaAlteracao', models.DateTimeField(auto_now=True)),
                ('telVara', models.CharField(blank=True, max_length=50, null=True)),
                ('emailVara', models.CharField(blank=True, max_length=50, null=True)),
                ('idForum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.forum')),
                ('idUserQueAlterou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='varas_alteradas', to=settings.AUTH_USER_MODEL)),
                ('idUserQueCadastrou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='varas_cadastradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='processo',
            name='idTblVara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.vara'),
        ),
    ]
