# Generated by Django 5.2.5 on 2025-08-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nometituloproc_statusproc_forum_processo_pasta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailPF', models.CharField(default='', max_length=100)),
                ('obs', models.CharField(default='', max_length=150)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('idTblPF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='emails_pf', to='core.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='EmailPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailPJ', models.CharField(default='', max_length=50)),
                ('obs', models.CharField(default='', max_length=100)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('idTblPJ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='emails_pj', to='core.pessoajuridica')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonePF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTelefone', models.CharField(default='', max_length=20)),
                ('obs', models.CharField(default='', max_length=50)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('idTblPF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='telefones_pf', to='core.pessoafisica')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonePJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTelefone', models.CharField(default='', max_length=20)),
                ('obs', models.CharField(default='', max_length=50)),
                ('dataCad', models.DateField(blank=True, null=True)),
                ('idTblPJ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='telefones_pj', to='core.pessoajuridica')),
            ],
        ),
    ]
