# Generated by Django 5.2.5 on 2025-08-23 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailpf_emailpj_telefonepf_telefonepj'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPerfilPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPerfilPessoa', models.CharField(default='0', max_length=50)),
                ('dataCad', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPessoa', models.CharField(blank=True, max_length=50, null=True)),
                ('dataCad', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('historico', models.IntegerField(blank=True, null=True)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
